//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarification_Ressource
    {
        public long ID { get; set; }
        public long FK_Ressource { get; set; }
        public long FK_Tarification { get; set; }
    
        public virtual Ressource Ressource { get; set; }
        public virtual Tarification Tarification { get; set; }
    }
}
