//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarification()
        {
            this.Tarification_Ressource = new HashSet<Tarification_Ressource>();
        }
    
        public long ID { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Tar3 { get; set; }
        public decimal Tar5 { get; set; }
        public Nullable<bool> IsAmo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarification_Ressource> Tarification_Ressource { get; set; }
    }
}
