//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarification()
        {
            this.Tarification_Ressource = new HashSet<Tarification_Ressource>();
        }
    
        public long ID { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Tar3 { get; set; }
        public decimal Tar5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarification_Ressource> Tarification_Ressource { get; set; }
    }
}
